### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by felixschndr** [mottobug/fritzbox-bandwidth-monitor#3]
Hey there,

I am trying to monitor the bandwidth use of my fritzbox and stumbled across your script. I am not using in a docker container but instead just using the shell script. 
However when starting the script I get this output:
```
HTTP/1.0 500 Internal Server Error
Content-Length: 198
Content-Type: text/html

<HTML><HEAD><TITLE>500 Internal Server Error (ERR_NO_MEMORY)</TITLE></HEAD><BODY><H1>500 Internal Server Error</H1><BR>ERR_NO_MEMORY<HR><B>Webserver</B> Thu, 13 Aug 2020 14:14:23 GMT</BODY></HTML>
HTTP/1.0 500 Internal Server Error
Content-Length: 198
Content-Type: text/html

<HTML><HEAD><TITLE>500 Internal Server Error (ERR_NO_MEMORY)</TITLE></HEAD><BODY><H1>500 Internal Server Error</H1><BR>ERR_NO_MEMORY<HR><B>Webserver</B> Thu, 13 Aug 2020 14:14:24 GMT</BODY></HTML>
0 days 00:00:00 h (online)
FRITZ!Box
```

So something is wrong with the HTTP request.

```
pi@rpi2helper:~ $ ./test.sh -t
OK
```
So this GET request works.

I am wondering on why this script doesn't use/need a username and password. My smart home server monitors the FritzBox as well (however it cant monitor the network usage) and this needs a password and a username for access.

I am using a FritzBox 7490.

**Comment by WernerBleisteiner** [comment]
Hi! 
Just installed it via docker on my RPi3.
But when I run 
`sudo docker run -d -p 80:80 fritzbox-bandwidth-monitor`
I get

`docker: Error response from daemon: driver failed programming external connectivity on endpoint angry_ride (d484095c811075addc4e0b26b5dad32c0ece1c5b3bb476598397df6476822164): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use.`
Im running von a FRitzBox 6490 and Fritz!OS 07.12.

Anything I might have missed?
Thanks

w

**Comment by WernerBleisteiner** [comment]
Sorry. My fault. Had forgotten that there's an nginx server already running and this causes a port conflict.
Now it runs fine.
But it won't stop using
`docker stop `
so I have to reboot for now.
